version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432 
    volumes:
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  server:
    build: server/
    command: yarn dev
    ports:
      - 5050:5050
  client:
    build: client/
    command: yarn dev
    network_mode: host
    depends_on:
      - server

volumes:
  db:
    driver: local